[llm]
api_base_url = "https://wanqing-api.corp.kuaishou.com/api/gateway/v1/endpoints"
api_key = "fs2wzco3o7haz38df1jo4vavnvauxtuz3f0b"
model_name = "ep-f3wkby-1769054358148733852"

[embedding]
api_base_url = "https://wanqing-api.corp.kuaishou.com/api/gateway/v1/endpoints"
api_key = "fs2wzco3o7haz38df1jo4vavnvauxtuz3f0b"
model_name = "ep-9kf01g-1762237999831608613"
